name: Feature request
description: Suggest an improvement or new capability
title: '[Feature]: '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Share the problem you’re trying to solve and how success should look.
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What’s missing or difficult today?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to happen?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or other options?
    validations:
      required: false
